using FollowUp.Domain.Common;
using FollowUp.Domain.Laboratories;
using FollowUp.Domain.Representatives;

namespace FollowUp.Domain.Operations;

public readonly record struct DailyVisitId(Guid Value)
{
    public static DailyVisitId New() => new(Guid.NewGuid());
    public override string ToString() => Value.ToString();
}

/// <summary>Driver/vehicle details captured when a collected visit is handed to a transfer rep (FR-6).</summary>
public sealed class TransferDetails : ValueObject
{
    public string DriverName { get; }
    public string DriverMobile { get; }
    public string? CarPlate { get; }

    public TransferDetails(string driverName, string driverMobile, string? carPlate)
    {
        if (string.IsNullOrWhiteSpace(driverName))
            throw new DomainException("Driver name is required to confirm a transfer.");
        if (string.IsNullOrWhiteSpace(driverMobile))
            throw new DomainException("Driver mobile is required to confirm a transfer.");
        DriverName = driverName.Trim();
        DriverMobile = driverMobile.Trim();
        CarPlate = string.IsNullOrWhiteSpace(carPlate) ? null : carPlate.Trim();
    }

    protected override IEnumerable<object?> GetEqualityComponents()
    {
        yield return DriverName;
        yield return DriverMobile;
        yield return CarPlate;
    }
}

/// <summary>
/// A single scheduled collection visit on the daily board (SRS FR-5, Workflows §2/§3). Generated by the
/// midnight board job from a lab's schedule; driven through Pending → Visited/Missed → Received.
/// Undo is refused once the visit has been transferred (the guard on the reverse edge).
/// </summary>
public sealed class DailyVisit : AggregateRoot<DailyVisitId>, IVersioned, IAuditable
{
    private DailyVisit() { } // EF

    private DailyVisit(DailyVisitId id, LaboratoryId labId, RepresentativeId? collectorRepId,
        DateOnly visitDate, TimeOnly scheduledTime)
        : base(id)
    {
        LaboratoryId = labId;
        CollectorRepId = collectorRepId;
        VisitDate = visitDate;
        ScheduledTime = scheduledTime;
        Status = VisitStatus.Pending;
    }

    public LaboratoryId LaboratoryId { get; private set; }

    /// <summary>Optimistic-concurrency token (Postgres xmin); concurrent visit updates conflict (409). Finding BRD-2.</summary>
    public uint RowVersion { get; private set; }
    public RepresentativeId? CollectorRepId { get; private set; }
    public DateOnly VisitDate { get; private set; }
    public TimeOnly ScheduledTime { get; private set; }
    public VisitStatus Status { get; private set; } = null!;

    public int? SampleCount { get; private set; }
    public DateTimeOffset? CheckedInAt { get; private set; }
    public string? CheckedInBy { get; private set; }

    // Check-in extras (reference parity): totals recorded with the visit + free-text notes.
    public int? TotalRequired { get; private set; }
    public int? RequestCount { get; private set; }
    public int? OutsourceCount { get; private set; }
    public string? Notes { get; private set; }

    public TransferDetails? Transfer { get; private set; }
    public RepresentativeId? TransferRepId { get; private set; }
    public DateTimeOffset? TransferConfirmedAt { get; private set; }

    public DateTimeOffset? ReceivedAt { get; private set; }

    /// <summary>The admin-checked verification flag (FR-5, requires VerifyDailyFollowup).</summary>
    public bool AdminChecked { get; private set; }

    public DateTimeOffset CreatedAt { get; private set; }
    public string CreatedBy { get; private set; } = null!;
    public DateTimeOffset? UpdatedAt { get; private set; }
    public string? UpdatedBy { get; private set; }

    /// <summary>Board generation — creates a Pending visit for a lab at a scheduled time (midnight job).</summary>
    public static DailyVisit Schedule(LaboratoryId labId, RepresentativeId? collectorRepId,
        DateOnly visitDate, TimeOnly scheduledTime) =>
        new(DailyVisitId.New(), labId, collectorRepId, visitDate, scheduledTime);

    /// <summary>Collector records the visit and its sample count (Pending → Visited).</summary>
    public void CheckIn(int sampleCount, string actor, DateTimeOffset when,
        int? totalRequired = null, int? requestCount = null, int? outsourceCount = null, string? notes = null)
    {
        Status.EnsureCanTransitionTo(VisitStatus.Visited);
        if (sampleCount < 0)
            throw new DomainException("Sample count cannot be negative.");
        if (totalRequired is < 0 || requestCount is < 0 || outsourceCount is < 0)
            throw new DomainException("Check-in counts cannot be negative.");
        Status = VisitStatus.Visited;
        SampleCount = sampleCount;
        CheckedInAt = when;
        CheckedInBy = actor;
        TotalRequired = totalRequired;
        RequestCount = requestCount;
        OutsourceCount = outsourceCount;
        Notes = string.IsNullOrWhiteSpace(notes) ? null : notes.Trim();
        Raise(new VisitCheckedIn(Id, LaboratoryId, sampleCount));
    }

    /// <summary>Reassigns the collector credited with this visit (check-in popup override).</summary>
    public void ReassignCollector(RepresentativeId? repId) => CollectorRepId = repId;

    /// <summary>Marks the visit missed (Pending → Missed): evening sweep or manual.</summary>
    public void Miss()
    {
        Status.EnsureCanTransitionTo(VisitStatus.Missed);
        Status = VisitStatus.Missed;
        Raise(new VisitMissed(Id, LaboratoryId));
    }

    /// <summary>Reverses a check-in (Visited → Pending). Refused once transferred (FR-5 guard).</summary>
    public void Undo()
    {
        if (TransferConfirmedAt is not null)
            throw new DomainException("Cannot undo a visit that has already been transferred.");
        Status.EnsureCanTransitionTo(VisitStatus.Pending);
        Status = VisitStatus.Pending;
        SampleCount = null;
        CheckedInAt = null;
        CheckedInBy = null;
    }

    /// <summary>Hands the collected samples to a transfer rep with driver details (FR-6).</summary>
    public void ConfirmTransfer(RepresentativeId transferRepId, TransferDetails details, DateTimeOffset when)
    {
        if (Status != VisitStatus.Visited)
            throw new DomainException("Only a checked-in (Visited) visit can be transferred.");
        TransferRepId = transferRepId;
        Transfer = details;
        TransferConfirmedAt = when;
    }

    /// <summary>Marks samples received at the laboratory (Visited → Received, FR-7).</summary>
    public void ReceiveAtLab(DateTimeOffset when)
    {
        Status.EnsureCanTransitionTo(VisitStatus.Received);
        Status = VisitStatus.Received;
        ReceivedAt = when;
        Raise(new VisitReceived(Id, LaboratoryId));
    }

    /// <summary>Elevated verification toggle (FR-5, VerifyDailyFollowup). Only a collected visit can be
    /// verified: the workflow verifies after check-in/receipt, and <see cref="RollsToMonthly"/> trusts
    /// <see cref="AdminChecked"/>, so a Pending/Missed visit must never carry it — otherwise a direct API call
    /// verifies a Pending visit that later rolls into monthly totals though never verified while collected
    /// (finding BRD-6). Mirrors the reference's Visited/Received-only verify gate.</summary>
    public void SetVerified(bool verified)
    {
        if (Status != VisitStatus.Visited && Status != VisitStatus.Received)
            throw new DomainException("Only a checked-in (Visited) or received visit can be verified.");
        AdminChecked = verified;
    }

    /// <summary>Whether this visit's samples count toward monthly totals at roll-over (verified &amp; received).</summary>
    public bool RollsToMonthly => AdminChecked && Status == VisitStatus.Received;
}
