BEGIN;
UPDATE ref_item SET real_name='اسوان' WHERE type='Governorate' AND name_en='A 1';
UPDATE area SET real_name='اسوان ١' WHERE name='A 11';
UPDATE area SET real_name='اسوان ٢' WHERE name='A 12';
UPDATE ref_item SET real_name='الاقصر' WHERE type='Governorate' AND name_en='A 2';
UPDATE area SET real_name='الاقصر ١' WHERE name='A 21';
UPDATE area SET real_name='الاقصر ٢' WHERE name='A 22';
UPDATE ref_item SET real_name='قنا' WHERE type='Governorate' AND name_en='A 3';
UPDATE area SET real_name='قنا ١' WHERE name='A 31';
UPDATE area SET real_name='قنا ٢' WHERE name='A 32';
UPDATE area SET real_name='قنا ٣' WHERE name='A 33';
UPDATE ref_item SET real_name='سوهاج' WHERE type='Governorate' AND name_en='A 4';
UPDATE area SET real_name='سوهاج ١' WHERE name='A 41';
UPDATE area SET real_name='سوهاج ٢' WHERE name='A 42';
UPDATE area SET real_name='سوهاج ٣' WHERE name='A 43';
UPDATE area SET real_name='سوهاج ٤' WHERE name='A 44';
UPDATE area SET real_name='سوهاج ٥' WHERE name='A 45';
UPDATE area SET real_name='سوهاج ٦' WHERE name='A 46';
UPDATE area SET real_name='سوهاج ٧' WHERE name='A 47';
UPDATE area SET real_name='سوهاج ٨' WHERE name='A 48';
UPDATE ref_item SET real_name='اسيوط' WHERE type='Governorate' AND name_en='A 5';
UPDATE area SET real_name='اسيوط ١' WHERE name='A 51';
UPDATE area SET real_name='اسيوط ٢' WHERE name='A 52';
UPDATE area SET real_name='اسيوط ٣' WHERE name='A 53';
UPDATE area SET real_name='اسيوط ٤' WHERE name='A 54';
UPDATE area SET real_name='اسيوط ٥' WHERE name='A 55';
UPDATE ref_item SET real_name='المنيا' WHERE type='Governorate' AND name_en='A 6';
UPDATE area SET real_name='المنيا ١' WHERE name='A 61';
UPDATE area SET real_name='المنيا ٢' WHERE name='A 62';
UPDATE area SET real_name='المنيا ٣' WHERE name='A 63';
UPDATE area SET real_name='المنيا ٤' WHERE name='A 64';
UPDATE area SET real_name='المنيا ٥' WHERE name='A 65';
UPDATE ref_item SET real_name='بنى سويف' WHERE type='Governorate' AND name_en='A 7';
UPDATE area SET real_name='بنى سويف ١' WHERE name='A 71';
UPDATE area SET real_name='بنى سويف ٢' WHERE name='A 72';
UPDATE area SET real_name='بنى سويف ٣' WHERE name='A 73';
UPDATE ref_item SET real_name='الفيوم' WHERE type='Governorate' AND name_en='A 8';
UPDATE area SET real_name='الفيوم ١' WHERE name='A 81';
UPDATE area SET real_name='الفيوم ٢' WHERE name='A 82';
UPDATE area SET real_name='الفيوم ٣' WHERE name='A 83';
UPDATE area SET real_name='الفيوم ٤' WHERE name='A 84';
UPDATE area SET real_name='الفيوم ٥' WHERE name='A85';
UPDATE ref_item SET real_name='الاسماعيليه' WHERE type='Governorate' AND name_en='B 3';
UPDATE ref_item SET real_name='المنوفيه' WHERE type='Governorate' AND name_en='B 4';
UPDATE area SET real_name='اشمون' WHERE name='B 41';
UPDATE area SET real_name='منوف' WHERE name='B 42';
UPDATE area SET real_name='شبين الكوم' WHERE name='B 43';
UPDATE ref_item SET real_name='القليوبيه' WHERE type='Governorate' AND name_en='B 5';
UPDATE area SET real_name='شبين القناطر' WHERE name='B 51';
UPDATE area SET real_name='بنها' WHERE name='B 52';
UPDATE area SET real_name='ميت كنانه' WHERE name='B 53';
UPDATE ref_item SET real_name='الشرقيه' WHERE type='Governorate' AND name_en='B 6';
UPDATE area SET real_name='بلبيس' WHERE name='B 61';
UPDATE area SET real_name='التل الكبير' WHERE name='B 62';
UPDATE area SET real_name='الصالحية' WHERE name='B 63';
UPDATE area SET real_name='الزقازيق' WHERE name='B 64';
UPDATE area SET real_name='ديرب نجم' WHERE name='B 65';
UPDATE area SET real_name='فاقوس' WHERE name='B 67';
UPDATE area SET real_name='الحسينيه' WHERE name='B 68';
UPDATE ref_item SET real_name='تارجت دلتا' WHERE type='Governorate' AND name_en='C 100';
UPDATE ref_item SET real_name='مسلم' WHERE type='Governorate' AND name_en='C400';
UPDATE ref_item SET real_name='عين شمس' WHERE type='Governorate' AND name_en='R 4';
UPDATE ref_item SET real_name='الخصوص' WHERE type='Governorate' AND name_en='R 5';
UPDATE ref_item SET real_name='عزبة النخل' WHERE type='Governorate' AND name_en='R 6';
UPDATE ref_item SET real_name='سيفتي الزقازيق' WHERE type='Governorate' AND name_en='S 1';
COMMIT;
